name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['4.0', '3.4']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Rubocop (Linter)
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
